# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ponpon Forever
    url: https://ponponforever.net/sf
  - name: qmo
    url: https://ponponforever.net/qmo
  - name: Ponpon Diary
    url: https://ponponforever.net/cestlavie
  - name: Yonia in Wonder World
    url: https://ponponforever.net/yoniagu
  - name: 三寶飯莊
    url: https://ponponforever.net/miao
  - name: 小步走。不放棄
    url: https://ponponforever.net/walking
  - name: 徐漢珊畫集
    url: https://ponponforever.net/sandymonblog
  - name: 漢珊畫集網誌
    url: https://ponponforever.net/sandymombennyradio
  - name: 無聊齋2
    url: https://ponponforever.net/boringer2
  - name: 無聊齋主看世界
    url: https://ponponforever.net/benny
  - name: 無聊齋日誌
    url: https://ponponforever.net/boringerlog
  - name: 章志彬的樂活網路電台
    url: https://ponponforever.net/bennyradio
  - name: 胖胖廚房筆記
    url: https://ponponforever.net/kitchen
  - name: 永遠的胖胖
    url: https://ponponforever.net/main
  - name: 詩班通訊
    url: https://ponponforever.net/cfcchc
  - name: 舊金山討論區
    url: https://ponponforever.net/forum
  - name: PONPON & BENNY'S TRAVEL LOG
    url: https://ponponforever.net/travel
  - name: Young Company, The Art of Glass
    url: https://ponponforever.net/samples/youngcom
  - name: 三寶飯莊(原)
    url: https://ponponforever.net/3cats
  - name: Ponpon's Family
    url: https://ponponforever.net/family
  - name: 貓咪首頁
    url: https://ponponforever.net/cats
  - name: Young Company, The Art of Glass
    url: https://ponponforever.net/samples/youngcom


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
